# Generated by Django 4.1.3 on 2022-11-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_name',
            field=models.CharField(default='Horror', max_length=100, verbose_name='name'),
        ),
    ]
